name: Deploy to QA

on:
  push:
    branches:
    - release/qa

jobs:
  check_commit:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check_commit_message.outputs.should_deploy }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check Commit Message
        id: check_commit_message
        run: |
          commit_message=$(git log -1 --pretty=%B)
          echo "Commit message: $commit_message"
          if [[ $commit_message == *"deploy: qa"* ]]; then
            echo "Commit message contains 'deploy: qa'."
            echo "::set-output name=should_deploy::true"
          else
            echo "Commit message does not contain 'deploy: qa'."
            echo "::set-output name=should_deploy::false"
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: check_commit
    if: needs.check_commit.outputs.should_deploy == 'true'
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:headless

    - name: Build
      run: npm run build:qa

    - name: Deploy
      if: success()
      run: aws s3 sync ./dist/cv-maker-webapp/browser s3://qa-cv-maker-webapp